/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Price { 'discounted' : [] | [bigint], 'original' : bigint }
export interface Product {
  'id' : string,
  'reviews' : Array<Review>,
  'name' : string,
  'createdBy' : Principal,
  'seller' : string,
  'emoji' : string,
  'category' : string,
  'badge' : [] | [string],
  'savings' : [] | [bigint],
  'rating' : [] | [bigint],
  'price' : Price,
  'location' : string,
}
export interface Review {
  'content' : string,
  'user' : Principal,
  'rating' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'addToWishlist' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      string,
      Price,
      string,
      string,
      string,
      [] | [bigint],
      Array<Review>,
      [] | [string],
      [] | [bigint],
    ],
    undefined
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<[string, bigint]>>,
  'getNewsletterSubscriptions' : ActorMethod<[], Array<string>>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'removeFromWishlist' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'updateCartQuantity' : ActorMethod<[string, bigint], undefined>,
  'updateProduct' : ActorMethod<
    [
      string,
      string,
      string,
      Price,
      string,
      string,
      string,
      [] | [bigint],
      Array<Review>,
      [] | [string],
      [] | [bigint],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];