/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Price = IDL.Record({
  'discounted' : IDL.Opt(IDL.Nat64),
  'original' : IDL.Nat64,
});
export const Review = IDL.Record({
  'content' : IDL.Text,
  'user' : IDL.Principal,
  'rating' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'reviews' : IDL.Vec(Review),
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'seller' : IDL.Text,
  'emoji' : IDL.Text,
  'category' : IDL.Text,
  'badge' : IDL.Opt(IDL.Text),
  'savings' : IDL.Opt(IDL.Nat64),
  'rating' : IDL.Opt(IDL.Nat),
  'price' : Price,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Price,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Vec(Review),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat64),
      ],
      [],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))], ['query']),
  'getNewsletterSubscriptions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'updateCartQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Price,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Vec(Review),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat64),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Price = IDL.Record({
    'discounted' : IDL.Opt(IDL.Nat64),
    'original' : IDL.Nat64,
  });
  const Review = IDL.Record({
    'content' : IDL.Text,
    'user' : IDL.Principal,
    'rating' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'reviews' : IDL.Vec(Review),
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'seller' : IDL.Text,
    'emoji' : IDL.Text,
    'category' : IDL.Text,
    'badge' : IDL.Opt(IDL.Text),
    'savings' : IDL.Opt(IDL.Nat64),
    'rating' : IDL.Opt(IDL.Nat),
    'price' : Price,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Price,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Vec(Review),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat64),
        ],
        [],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getNewsletterSubscriptions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'updateCartQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Price,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Vec(Review),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat64),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };